import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;

import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        SqlSession sqlSession = MyBatisUtil.getSqlSession();
        PositionMapper positionMapper = sqlSession.getMapper(PositionMapper.class);
        AccountMapper accountMapper = sqlSession.getMapper(AccountMapper.class);
        OrderMapper orderMapper = sqlSession.getMapper(OrderMapper.class);
        positionMapper.deleteAll();
        orderMapper.deleteAll();
        accountMapper.deleteAll();
        sqlSession.commit();
        MatchingEngine matchingEngine = new MatchingEngine();
        matchingEngine.start();
    }
}
